### ISSUE TITLE
Adds custom build image page

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-bootc#141]
### Is your enhancement related to a problem? Please describe

it looks like a friction point from the beginning was to not use quick pick but use forms

I see requests about 'Form based' widget displaying a form rather than quickpick

But I think it won't solve the root issue that you want to customize the workflow with shortcuts, displaying icons at some very specific places, etc

About generating forms i think some people invested (like https://eclipse.dev/ecp/emfforms/ but is it something appealing on UX side at the end, I would not go there)

### Describe the solution you'd like

I think a working approach would be to replace dialog by a custom Webview

Probably we need to tune the webview support, I see the required features like:
 - do not display it in the left navbar
 - reveal the webview (programmatically, not expecting the user would need to perform an action)

Then you could display a very customized page with a fancy look&feel

**Comment by benoitf** [comment]
created dependencies in Podman Desktop
- https://github.com/containers/podman-desktop/issues/5924
- https://github.com/containers/podman-desktop/issues/5925

it does not prevent to start the work in parallel to see if it fits the needs

**Comment by cdrage** [comment]
Changed the title as it has been brought up we are keeping quickpick for-now, until we implement a way to "auto propagate" the build selection screen when clicking on that certain image in the image list @deboer-tim
