### ISSUE TITLE
Documenting installation from a script

### ISSUE THREAD

**Issue by lmilbaum** [containers/podman-desktop-extension-bootc#143]
### Is your enhancement related to a problem? Please describe

I'm preparing a bootc image which will be used for provisioning an environment for AI workflows testing. The extension will be installed in a container image during build time. Having said that, a CLI to install the extension is required and will be placed in the container image Containerfile. 

### Describe the solution you'd like

A CLI command(s) which installs the extension in a container image

**Comment by deboer-tim** [comment]
I'm sorry, but I don't understand. Are you installing Podman Desktop + bootc extension in a container for build time? Normally I would expect the underlying CLI tools (Podman, Bootc image builder) to be used directly in scripted environments.

**Comment by lmilbaum** [comment]
> I'm sorry, but I don't understand. Are you installing Podman Desktop + bootc extension in a container for build time? Normally I would expect the underlying CLI tools (Podman, Bootc image builder) to be used directly in scripted environments.

That could be an option but not preferable as the goal is to use an environment as similar as possible to a user who is interested to run an AI workflow on his laptop.

**Comment by cdrage** [comment]
> > I'm sorry, but I don't understand. Are you installing Podman Desktop + bootc extension in a container for build time? Normally I would expect the underlying CLI tools (Podman, Bootc image builder) to be used directly in scripted environments.
> 
> That could be an option but not preferable as the goal is to use an environment as similar as possible to a user who is interested to run an AI workflow on his laptop.

Sorry, but I'm a bit confused too. 

podman-desktop-extension-bootc would be the GUI-only tool which is just a wrapper over https://github.com/osbuild/bootc-image-builder do you mean installing https://github.com/osbuild/bootc-image-builder within a container image?

**Comment by lmilbaum** [comment]
I had hopped to install podman desktop and the plugins in a bootc image which eventually be used for provisioning an AWS instance. I'll be able to run manual and automatic tests on that instance.

**Comment by cdrage** [comment]
> I had hopped to install podman desktop and the plugins in a bootc image which eventually be used for provisioning an AWS instance. I'll be able to run manual and automatic tests on that instance.

Ahhh, I see now. I'm assuming the bootc image is GUI-based?

There's no implementation at the moment to install an extension through the CLI for Podman Desktop right now. 

I think last time I tried installing the GUI desktop though for the bootc centos7 image, it had failed, which image are you using that you're able to create a GUI out of a bootc image?

**Comment by lmilbaum** [comment]
> > I had hopped to install podman desktop and the plugins in a bootc image which eventually be used for provisioning an AWS instance. I'll be able to run manual and automatic tests on that instance.
> 
> Ahhh, I see now. I'm assuming the bootc image is GUI-based?
> 
> There's no implementation at the moment to install an extension through the CLI for Podman Desktop right now.
> 
> I think last time I tried installing the GUI desktop though for the bootc centos7 image, it had failed, which image are you using that you're able to create a GUI out of a bootc image?

This is the repo I'm working on provisioning the test environment. 
https://gitlab.com/bootc-org/tests/testing-framework/provisioning-bootc

**Comment by deboer-tim** [comment]
Podman Desktop extensions are just OCI images, unzipped in Podman Desktop's config folder. Even if this request is just for bootc extension, I think this should be moved to containers/podman-desktop as it can be done generically - i.e. either we can document/write a script to do it, or there could be a flag on the extension urls that would not only bring up the extension page but perform the install, e.g. `podman-desktop:extension/redhat.redhat-authentication?install`

**Comment by lmilbaum** [comment]
> Podman Desktop extensions are just OCI images, unzipped in Podman Desktop's config folder. Even if this request is just for bootc extension, I think this should be moved to containers/podman-desktop as it can be done generically - i.e. either we can document/write a script to do it, or there could be a flag on the extension urls that would not only bring up the extension page but perform the install, e.g. `podman-desktop:extension/redhat.redhat-authentication?install`

I've reached out to the podman desktop QE folks.  Actually, there is a meeting today to discuss their testing framework.

**Comment by deboer-tim** [comment]
This is not a bootc extension-specific issue. If this was not resolved please reopen here: https://github.com/containers/podman-desktop/issues
