### ISSUE TITLE
Can't build ISO with target arch... even the current one

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-bootc#149]
### Bug description

If you try to build an iso with the target arch option, it fails:
```
Generating manifest-iso.json ... WARNING: target-arch is experimental and needs an installed 'qemu-user' package
panic: cannot build iso for different target arches yet

goroutine 1 [running]:
main.cmdBuild(0x400013d700?, {0x40006b6770, 0x1, 0x7})
	/build/bib/cmd/bootc-image-builder/main.go:274 +0x864
github.com/spf13/cobra.(*Command).execute(0x40006bc000, {0x40006b6700, 0x7, 0x7})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x4000145b00)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.run()
	/build/bib/cmd/bootc-image-builder/main.go:373 +0x530
main.main()
	/build/bib/cmd/bootc-image-builder/main.go:377 +0x1c
```

Unfortunately, it does this for either arch 🤦🏼‍♂️ so you can't build an ISO on 0.3.0.

### Operating system

macOS & windows

### Version

next (development version)

**Comment by mrguitar** [comment]
I'm getting this same error using PD 1.8 and podman machine 5 rc7. I got the same error w/ 4.9. I'm sure I'm doing something wrong, but I don't see a "qemu-user" package in brew. This system does have qemu 8.2.1 installed. I am using the vfkit as the hypervisor. Could that be an issue?

**Comment by deboer-tim** [comment]
Hi @mrguitar. I'm going to work on pulling a new version of bootc image builder where this is fixed... but unfortunately the resulting image still won't boot: https://github.com/osbuild/bootc-image-builder/issues/233. Work on it is active, hopefully we can get this resolved soon.

**Comment by cdrage** [comment]
We could either close this or open a new issue.. right now building .iso works for the current arch (fixed upstream, and our fix here too), but not cross-arch (yet).

**Comment by deboer-tim** [comment]
I opened this really for the 'you can't build with the current arch as target' issue, so I'm going to close.

We could open another issue to track cross-arch iso building, but I don't feel strongly about it since it is a bib limitation that we're not trying to avoid for the user nor would react to.
