### ISSUE TITLE
Feat: Get my first bootc image

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-bootc#158]
### Is your feature request related to a problem? Please describe

Even after having installed the extension, there is no easy way to know what the extension provides - how to use it. At least not from within Podman Desktop. One would be required to come to the readme.md of the extension. 

### Describe the solution you'd like

It would be nice if there was a way to display an easy "onboarding" or "discover" extension page from within Podman Desktop. The goal for a end-user would be to build a first bootc image - but also being walked through the different steps, so important explanations and concepts are also getting introduced.

### Additional context

Not sure, where to surface that into the UI today.

**Comment by deboer-tim** [comment]
IMHO the general 'extensions should have a way to tell users what's new or how to access it' is a Podman Desktop issue, and updating Settings > Extensions has not been a priority. It would be nice to at least show a readme there.

Without this, the only place where extensions can really put anything is a webview. This isn't a great general solution, but we've hoping it can help with this, and is being planned via #150.

**Comment by cdrage** [comment]
We should use an "official" example from: https://gitlab.com/bootc-org/examples that is tried-and-tested / checked on CI.

Based on our discussion in #150 this issue would also require a "pull this image" button as well, right? In order to successfully retrieve your first bootc image.

**Comment by cdrage** [comment]
Now that #150 is closed, I believe that we could close this as we have the "Pull" and "Build" buttons now built-in to the dashboard.

**Comment by deboer-tim** [comment]
Marking this as complete, please open a new issue if you think there's anything still to do.
