### ISSUE TITLE
Should check if podman 5.0 or not

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#168]
### Is your enhancement related to a problem? Please describe

5.0 is a requirement and we should be checking for that. 

### Describe the solution you'd like

Fail if below 5.0 since we cannot build multi-arch on mac m1 without 5.0

**Comment by cgwalters** [comment]
Ah yes, OK so I ran into this.  Just to add a cookie here for others, the error string is `failed to parse query parameter 'platform'`

**Comment by cgwalters** [comment]
(OK, I updated to 5.0 on the Mac, ran into https://github.com/containers/podman/issues/22109 ...trying to use latest git)
