### ISSUE TITLE
Review of the telemetry events

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-bootc#179]
### Is your enhancement related to a problem? Please describe

We'd like to review the telemetry events we are reporting to ensure we have proper information about how the users are using the extension and where they are eventually facing challenges

### Describe the solution you'd like

We'd like to review the telemetry events we are reporting to ensure we have proper information about how the users are using the extension and where they are eventually facing challenges

**Comment by deboer-tim** [comment]
Notes from meeting this morning:
- [ ] Log event for clicking on pull in the welcome
- [ ] Log event when switching to the build page
- [ ] Chart to show type of images being built
- [ ] Chart to show architecture of images being built

**Comment by deboer-tim** [comment]
Telemetry in, charts updated, but forgot to list the implied charts required for the new telemetry. Will add these, then close.

**Comment by cdrage** [comment]
https://github.com/containers/podman-desktop-extension-bootc/pull/288 is closed, I believe we can close this now?

**Comment by deboer-tim** [comment]
I've verified all events are being output and appear in Segment, and have drafts of all charts. Closing.
