### ISSUE TITLE
Allow being able to select multiple outputs (checkboxes?) 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#182]
### Is your enhancement related to a problem? Please describe

https://github.com/osbuild/bootc-image-builder/pull/225 has been merged and the CLI can now build multiple images at the same time.

### Describe the solution you'd like

This should go in as a follow up PR after #180

**Comment by deboer-tim** [comment]
Didn't notice this while searching yesterday, but this is the same thing as #216, which now has a PR up. Closing this as a dupe and tracking via #216.
