### ISSUE TITLE
Add vdmk option

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#183]
### Is your feature request related to a problem? Please describe

Add the VMDK option: https://github.com/osbuild/bootc-image-builder/pull/251 to webview + quickpick

### Describe the solution you'd like

Added to webview and quickpick

**Comment by vrothberg** [comment]
This came up yesterday in the context of https://issues.redhat.com/browse/HMS-3663.
@cdrage is this doable by 1.0?  I added it to the milestone for now.

**Comment by cdrage** [comment]
This will be a very quick fix (just need to add the option on the webview + quickpicks).

It'll be done by 1.0 👍

**Comment by vrothberg** [comment]
Awesome, thank you, @cdrage !
