### ISSUE TITLE
Dashboard: Details page similar to other parts of Podman Desktop

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#203]
### Is your feature request related to a problem? Please describe

Epic? 

Would like to see all the build information (what was selected, details, etc.)

As well as: Current logs.

### Describe the solution you'd like

When clicking on the build name, we should have a details page similar to other aspects of PD.

**Comment by deboer-tim** [comment]
I created a duplicate and didn't realize it, this was delivered via #856.
