### ISSUE TITLE
Add E2E tests run as part of PR check

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-bootc#213]
### Is your enhancement related to a problem? Please describe

We are proposing new CI workflows in the repo, there is a CI to be run on after merge (https://github.com/containers/podman-desktop-extension-bootc/pull/208). 
To get better and faster results of the changes done in code and while being suggested (new PR), we should have e2e tests run on PR check.

### Describe the solution you'd like

Idea would be to include new steps in PR check workflow (https://github.com/containers/podman-desktop-extension-bootc/blob/main/.github/workflows/pr-check.yaml), similar to what e2e-test-main (once merged) workflow offers, except a couple of adjustments.

It would be ideal to have extension image to be built locally (I guess we cannot really push into registry since we are on PR check and cannot use secrets), then the local image would be used as the one to be installed as an extension in the tests, we can probably use env.vars.  to get image uri.

**Comment by cbr7** [comment]
@deboer-tim @cdrage Hey guys in order to get the e2e tests running on pr check we'd need to be able to build the extension locally on the GHA runner, is the process to how to do that available anywhere?

**Comment by cdrage** [comment]
> @deboer-tim @cdrage Hey guys in order to get the e2e tests running on pr check we'd need to be able to build the extension locally on the GHA runner, is the process to how to do that available anywhere?

Hi! It's on the README:

https://github.com/containers/podman-desktop-extension-bootc?tab=readme-ov-file#contributing

**Comment by cbr7** [comment]
@cdrage great, thank you
