### ISSUE TITLE
Ability to select multiple image types in one pass

### ISSUE THREAD

**Issue by mrguitar** [containers/podman-desktop-extension-bootc#216]
### Is your enhancement related to a problem? Please describe

bootc makes it easy to target multiple platforms with a single container image. Yet the plugin makes me create disk images for a single platform at a time which is time consuming for the user.

### Describe the solution you'd like

Maybe changing the radial button to a check box and being able to select multiple image types and have the extension handle queuing them up to BIB on the user's behalf. 

### Additional context

"I need a Qcow2, ami, and vmdk. ......tada!!!"  :)

**Comment by vrothberg** [comment]
Thanks for reaching out, @mrguitar!

Is this a nice to have for you or something that will get in the way of users?

Cc: @cdrage @deboer-tim

**Comment by vrothberg** [comment]
So instead of a single item, you like to have some kind of check boxes a user could click?

![Screenshot 2024-03-21 at 15 32 48](https://github.com/containers/podman-desktop-extension-bootc/assets/11679875/f474bcb8-8dda-4e0d-bae5-faddd9d6bb0c)

**Comment by vrothberg** [comment]
Thanks!  I guess it makes sense to cover both workflows but I will let the team decide what's best.

**Comment by cdrage** [comment]
Thank you for adding this! This has already been implemented upstream on bootc-image-builder, we just need to play catch-up to add it and update our "history.json" outputs (we output to history what the user has selected).

We will most likely be adding this to webview only as we are most likely deprecating quickpick.

cc @deboer-tim

**Comment by mrguitar** [comment]
Awesome to hear it's in BIB already. Sorry I'm not familiar with webview vs quickpick. Is the quickpick shown in one of the above screenshots? or is it something else? .....please forgive my ignorance.  :)

**Comment by cdrage** [comment]
> Awesome to hear it's in BIB already. Sorry I'm not familiar with webview vs quickpick. Is the quickpick shown in one of the above screenshots? or is it something else? .....please forgive my ignorance. :)

Haha no worries! The "quickpick" is this one:

![Screenshot 2024-03-21 at 11 16 47 AM](https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/bda828d9-00d4-43ac-9acd-cddbecb54641)

Which you can get to by clicking the action next to an image.

The "webview" is here:

![Screenshot 2024-03-21 at 11 17 08 AM](https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/bf66639d-0868-4011-8b74-5d0d70546ddd)

Which is from the navbar on the left.

The plan is to have the action on the image list, take you to the webview with the image pre-selected, as our form is slowly becoming more complicated.

**Comment by mrguitar** [comment]
ok perfect. That was my guess, but I wasn't sure. Thanks for clarifying, and I agree the webview is where we need this.

**Comment by deboer-tim** [comment]
Thanks to @cdrage for noticing this was already in upstream. While trying to work on a different issue today I noticed the work for this was simple and literally in the exact same ~5 places, so I did both at the same time. PR #223 up.

**Comment by mrguitar** [comment]
AMAZING! I can't wait to try it. Thank you so much for knocking this out!

**Comment by vrothberg** [comment]
> AMAZING! I can't wait to try it. Thank you so much for knocking this out!

Ready to test in https://github.com/containers/podman-desktop-extension-bootc/pull/223, @mrguitar

**Comment by mrguitar** [comment]
I'd love to test it out, but I'm not really setup to build this on my new system. Is there a container image I can pull?

**Comment by deboer-tim** [comment]
Unfortunately we don't produce container images until the PR is merged, and an earlier/bigger PR got in first that creates a conflict. @cdrage is working on the fix, shouldn't take us long.
