### ISSUE TITLE
Outdated container examples

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#219]
### Bug description

Our container images use an outdated image (fedora eln), and we should instead point to upstream examples which have tests: https://gitlab.com/bootc-org/examples

### Operating system

mac m1

### Version

next (development version)

**Comment by cdrage** [comment]
Closed by https://github.com/containers/podman-desktop-extension-bootc/pull/222

**Comment by vrothberg** [comment]
https://github.com/containers/podman-desktop-extension-bootc/pull/222 merged, closing.
