### ISSUE TITLE
Warn for not enough RAM (need at least 6GB) for Podman Machine.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#221]
### Is your enhancement related to a problem? Please describe

If you do not have enough ram you'll encounter "out of space" issues.

As well as not being able to complete the build.

The default amount of ram (2GB) from podman machine creation is not enough 

### Describe the solution you'd like

Warning that your podman machine is below 6GB of ram and will not be compatible.

### Additional context

Reference: https://github.com/osbuild/osbuild/pull/1673

**Comment by benoitf** [comment]
if there is a common pattern then a component could be added in the podman UI library and then consumed by both extensions

**Comment by cgwalters** [comment]
> Reference: https://github.com/osbuild/osbuild/pull/1673

That one is fixed though right?

I am not aware of a reason that the build process should require substantial RAM otherwise, and it'd be indicative of a bug.

**Comment by deboer-tim** [comment]
We're using image builder latest-1710916056 from March 20. I don't know how to track individual fixes, but that's the same day 1673 went in and it's the last build from that day, so odds are good we're running it. QE has seen an ISO fail on a 6Gb machine (or multiple builds at the same time fail on a larger machine).

So if 2Gb should be enough and we just need to pick up a newer bib that's excellent. If not, ideally the recommendation should come from 322, and we'll use this issue to prompt the user if the current machine falls below the recommendation.
