### ISSUE TITLE
Support for different disk image builders

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-bootc#238]
### Is your enhancement related to a problem? Please describe

Long term there may be multiple disk image builder containers, or versions of each. Containers may want to indicate which builder they prefer or maybe have a minimum requirement.

### Describe the solution you'd like

We need to understand the long term tagging strategy/evolution [1] of the disk image builder, how containers might indicate their requirements [2], and come up with a plan for how we'd support this in the tools, ideally without any new cognitive load on the user (i.e. no new UI or prompts, it just does the right thing).

[1] https://github.com/osbuild/bootc-image-builder/issues/111
[2] https://github.com/CentOS/centos-bootc/pull/453

**Comment by cgwalters** [comment]
BTW every time someone says "image" I usually make them clarify "disk image" or "container image"...this one should definitely say "disk image".

**Comment by deboer-tim** [comment]
Good point :), updated

**Comment by cdrage** [comment]
RHEL image builder has now been added :) https://github.com/containers/podman-desktop-extension-bootc/issues/428

**Comment by cdrage** [comment]
Can we close this since RHEL image builder has been added? Or should we still keep this open for "custom" image builders?

**Comment by deboer-tim** [comment]
Yup, we should close.
