### ISSUE TITLE
Rejecting the overwrite request when trying to build over an existing image is not handled gracefully

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop-extension-bootc#260]
### Bug description

If the user rejects the request to overwrite the files in the provided folder when building a bootc image the screen will gray out and freeze for a few seconds and afterwards a time out error will be displayed.

https://github.com/containers/podman-desktop-extension-bootc/assets/106525396/4686f09a-77b2-4970-a5a9-f5a6f6edb938

### Operating system

macOs

### Version

next (development version)

### Steps to reproduce

1. Build a bootc image in a folder.
2. Begin creating a new bootc image and provide the same folder name as in step one.
3. When the request to overwrite popup is displayed select the `No` option.
4. Notice that the screen grays out and freezes for a few seconds and afterwards a time out error is provided.

**Comment by deboer-tim** [comment]
Confirmed this is a bug, but it is a dup of #200.
