### ISSUE TITLE
Multi type builds fail if ISO type is selected

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop-extension-bootc#269]
### Bug description

It seems that bootc builds fail if the user tries to create a multiple type build in which he includes the ISO type, however if ISO is not selected multiple type builds seem to be working fine.

### Operating system

macOS

### Version

next (development version)

### Steps to reproduce

1. Have bootc extension installed.
2. Go to create a disk image menu.
3. Select multiple types of images to build from the checkbox and include ISO as one of the types.
4. Start the build process.
5. Notice that the build will error out.

### Additional context

Relevant log files can be found in the slack message thread at: https://redhat-internal.slack.com/archives/C06GF1TSARF/p1712220390126359

**Comment by deboer-tim** [comment]
It looks like image builder team will try to fix the current 'can't build for local target arch' issue, but cross-arch building of iso is not a short-term goal: https://github.com/osbuild/bootc-image-builder/issues/316.

I'll use this issue to change our UI/build args to support this.
