### ISSUE TITLE
Building container disk image fails on linux

### ISSUE THREAD

**Issue by rostalan** [containers/podman-desktop-extension-bootc#271]
### Bug description

Tried to build disk image, got this error:
![image](https://github.com/containers/podman-desktop-extension-bootc/assets/75624842/0820b1d2-5d7c-4789-a17f-1a885c02b3f7)
Testing on linux, so cannot recreate podman machine or set it as rootful, afaik.

### Operating system

Fedora 39

### Version

next (development version)

**Comment by benoitf** [comment]
@rostalan you need to use a podman machine on Linux

**Comment by benoitf** [comment]
see https://github.com/containers/podman-desktop-extension-bootc?tab=readme-ov-file#requirement-2-rootful-mode-on-podman-machine (Linux section)
