### ISSUE TITLE
Multi-architecture support for building (example, building an x86 image using an ARM machine)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#28]
I should be able to build a amd64 bootable container using my Mac (arm64) and then be able to plug it into an amd64 machine / use it.

**Comment by cdrage** [comment]
Tracked upstream via: https://github.com/osbuild/bootc-image-builder/issues/153

**Comment by deboer-tim** [comment]
Reopening due to complications with making sure we have a usable image at the end.

**Comment by cdrage** [comment]
https://github.com/containers/podman/issues/21882 has been closed, the images updated, and can confirm that we can now build multi-arch.

However... it is 5.0 only.

**Comment by ericcurtin** [comment]
This will be super useful for Automotive... In Automotive, there's a lot of demand to do the opposite... Building an ARM image on x86

**Comment by vrothberg** [comment]
@cdrage are we waiting for the 5.0 release before closing this issue?

**Comment by cdrage** [comment]
> @cdrage are we waiting for the 5.0 release before closing this issue?

Yes. As well as having more documentation on 5.0 / validation checks within the extension.

**Comment by cdrage** [comment]
Keeping issue open until we have more documentation on the main page (updated with "build image" web view part).

**Comment by cdrage** [comment]
@deboer-tim @slemeur 

We have added the updated image as per #178 

Documentation has been updated to note that it has to be 5.0

We plan to update the documentation once we have #150 in

Should we close this issue now?

**Comment by deboer-tim** [comment]
Yes, I am fine closing. I'm guessing we will still have some minor tweak or doc update, but the function is in and working on our part so no need to keep this open.

**Comment by vrothberg** [comment]
Nice work, everyone!
