### ISSUE TITLE
should not recommend --net=host

### ISSUE THREAD

**Issue by cgwalters** [containers/podman-desktop-extension-bootc#357]
### Bug description

https://github.com/containers/podman-desktop-extension-bootc?tab=readme-ov-file#run-the-container-with-the-following-command-or-through-the-podman-desktop-ui

The usage of the combination of `--privileged` and `--net=host` means that e.g. OpenSSH inside the container will try to (and hopefully, fail) to claim the *host*'s port `22`.  

We'll need to build up canonical examples for doing this; this relates at least to https://github.com/containers/podman/issues/5188 for example.

I think for now I would just link to that issue and say that tested/supported and sane way to do this is forthcoming.  (But we could have that command in a `<details>` for those who really want it)

**Comment by cdrage** [comment]
I agree.. As much as it's convenient to test, this is untested (like the docs). I think we should remove it until we have a better solution in the future.

**Comment by cdrage** [comment]
@deboer-tim
