### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-bootc#36]
Need to have basic unit tests enabled, and automated e2e flow as much as possible.

**Comment by cbr7** [comment]
I've created issue https://github.com/containers/podman-desktop-extension-bootc/issues/117 to track the e2e test effort separately from the unit test effort.

**Comment by cbr7** [comment]
This was being tracked as part of the https://github.com/containers/podman-desktop-extension-bootc/issues/117 which was completed. Closing this.
