### ISSUE TITLE
Adopt UI component library

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-bootc#368]
### Epic domain

- [x] #369
- [x] #370
- [ ] #371
- [x] #372
- [x] #373
- [x] #374
- [x] #375
- [ ] #376
- [x] #377
- [x] #378
- [x] #379
- [x] #380
- [x] #381

**Comment by deboer-tim** [comment]
#376 is stalled waiting for a component in Podman Desktop and all other work is complete. Since it is already being tracked via an issue I don't think it's worth keeping an epic open as well, so I'm marking this as done and closing.
