### ISSUE TITLE
Build multiple image types at once

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-bootc#37]
Just like building a container image, it should be possible to select two or more image types and generate both in one flow.

**Comment by benoitf** [comment]
with `canPickMany: true` parameter it's possible to show multiple choice from UI

**Comment by deboer-tim** [comment]
👍🏼 We are just waiting to see if image builder will support multiple in one call or needs to be called more than once.

Forgot to mention in description: multiple could mean e.g. iso + raw, or iso in two architectures.

**Comment by deboer-tim** [comment]
Just noting: it doesn't look like the builder will add this capability, but you can now manually kick off multiple builds at once. The remaining work would be for us to allow multi-select and kick off more than one build.
