### ISSUE TITLE
While using build bootc image and selecting more than one architecture type with podman desktop bootc extension  image build process  fails 

### ISSUE THREAD

**Issue by veniceofcode** [containers/podman-desktop-extension-bootc#414]
### Bug description

<img width="1509" alt="Screenshot 2024-04-30 at 12 17 51 AM" src="https://github.com/containers/podman-desktop-extension-bootc/assets/93591339/365fa6e9-2c65-443c-8832-d16488fd9ed5">

### Operating system

mac OS Sonoma 14.4.1

### Version

next (development version)

### Additional context

Is this expected behavior ?

**Comment by deboer-tim** [comment]
Podman Desktop 1.9 did not support building multi-platform images. This was fixed/added in 1.10 via this PR: https://github.com/containers/podman-desktop/pull/6792. You can pull the latest code now, or wait a few days for 1.10 to finish testing and be released.
