### ISSUE TITLE
Cannot build ARM64 bootc images on windows

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop-extension-bootc#429]
### Bug description

I seems that right now it's not possible to build ARM64 arch images on windows operating system, even though building AMT64 arch types is working fine.

### Operating system

Windows 11

### Version

next (development version)

### Steps to reproduce

1. Build base image for ARM64 architecture in PD on Windows.
2. Using that base image try to create an ARM64 type bootc image.
3. Notice that the build will fail quickly after startup.

[image-build (1).log](https://github.com/containers/podman-desktop-extension-bootc/files/15189933/image-build.1.log)

### Relevant log output

```shell
Generating manifest manifest-raw.json
WARNING: target-arch is experimental and needs an installed 'qemu-user' package
Error: cannot build manifest: cannot get rootfs type for container: failed to run bootc install print-configuration: exit status 125, stderr:
Error: no container with name or ID "bdfa60e4c7736f74fc4c644d2d70a671368495930d21a07e873c07c696b8b277" found: no such container
2024/05/02 14:24:16 error: cannot build manifest: cannot get rootfs type for container: failed to run bootc install print-configuration: exit status 125, stderr:
Error: no container with name or ID "bdfa60e4c7736f74fc4c644d2d70a671368495930d21a07e873c07c696b8b277" found: no such container
```

**Comment by cdrage** [comment]
FYI this is an issue upstream and is being tracked here now: https://github.com/containers/podman/issues/19961

Closing as notfix since it's an upstream issue.
