### ISSUE TITLE
UX: need global preference for where to store disk images once built

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop-extension-bootc#47]
Right now when the user builds a disk image, we prompt them where on disk to store the image. It would be better to have a preference/setting that the user picks a directory to put them in (even better we pick a default - maybe ~ or ~/Downloads - or their equivalents based on whatever OS being used - this is the pattern web browsers follow.) 

Then the user doesn't have to figure this out every time they build an image and they know where to expect to find them.

**Comment by deboer-tim** [comment]
+1 to having default per-OS. Instead of a preference, we were thinking of just remembering the last path though.

**Comment by mairin** [comment]
> +1 to having default per-OS. Instead of a preference, we were thinking of just remembering the last path though.

Default per OS and remembering last path sounds like a good approach to me. 👍

**Comment by deboer-tim** [comment]
Closing as delivered: PR #73 delivered a history list where we store where all disk images are generated (because this full list might be useful later). When you generate another image, we just pre-fill the last folder.
