### ISSUE TITLE
Support using build config (username, password, ssh key, kernel, kickstart).

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#471]
### Is your enhancement related to a problem? Please describe

We have build config on the bootc-image-builder: https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#-build-config but not in GUI.

### Describe the solution you'd like

* Short term solution: Be able to pass in a filepath to the `config.toml`
* Long term solution: Make it a form so that we can enter our own user / password / ssh key / kickstart / etc that will auto create the config.toml / pass it in.

_No response_

**Comment by cdrage** [comment]
FYI marking this as critical @nichjones1 @slemeur as we've been getting this request a few times now in the bootc  channels, let me know if that's okay.

**Comment by deboer-tim** [comment]
Switched back to enhancement as there are no children and we don't target epics to sprint.
