### ISSUE TITLE
Initial light mode support

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop-extension-bootc#536]
### Is your enhancement related to a problem? Please describe

Most light mode support is coming just by reusing components from Podman Desktop, but we're now in the odd place where if we release with the new library components and Podman Desktop starts exposing experimental light mode support, some of the main text and UI in this extension will switch to light mode and expose some issues.

### Describe the solution you'd like

Adopt light mode for most of the UI that we won't get for free from the components - picking up existing style colors from variables.

**Comment by cdrage** [comment]
Split into two issues:

- [ ] https://github.com/containers/podman-desktop-extension-bootc/issues/539
- [ ] https://github.com/containers/podman-desktop-extension-bootc/issues/540

**Comment by deboer-tim** [comment]
Fixing a minor issue with #709, but the rest of this is complete. Marking done and closing.
