### ISSUE TITLE
Light mode for form

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#540]
### Is your enhancement related to a problem? Please describe

Added light mode for form

### Describe the solution you'd like

Light mode

**Comment by deboer-tim** [comment]
I'm going to mark this done. All light mode variables are being picked up from Podman Desktop correctly, and fonts/size match the rest of the UI. The biggest remaining issue is the select dropdown at the top of the form, but that is an issue that needs to be solved in Podman Desktop and then we'll pick up the component here later.
