### ISSUE TITLE
Light mode "missing" in progress icon

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#561]
### Bug description

https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/a4809d54-4d9e-4e0b-a0f2-ccf28e9b49f8

In progress icon is missing on initial starting (pulling the bib image)

### Operating system

mac m1

### Version

next (development version)

**Comment by deboer-tim** [comment]
Should be fixed by https://github.com/containers/podman-desktop/issues/7728.
