### ISSUE TITLE
Build icon showing up strange in light mode

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#622]
### Bug description

![Screenshot 2024-07-11 at 9 40 19 AM](https://github.com/containers/podman-desktop-extension-bootc/assets/6422176/5663c698-a1ef-4e02-b016-240fb987a5d2)

Looks like it's no longer light colour?

I think it's from the status icon update changes we did?

cc @deboer-tim 

### Operating system

mac M1

### Version

next (development version)

**Comment by deboer-tim** [comment]
It is this issue: https://github.com/containers/podman-desktop/issues/7728 (since we copied code). We can do the same fix, but StatusIcon is now in the API - more work to map statuses but might be better long-term solution.

**Comment by deboer-tim** [comment]
This is fixed in the latest version of the library - but was also fixed indirectly via https://github.com/containers/podman-desktop/pull/8061. Nothing to do here, so closing.
