### ISSUE TITLE
Move our images and videos to docs branch

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#66]
### Is your enhancement related to a problem? Please describe

We should place all our videos / pictures into a branch rather than having to rely on storing it on github cache / imgur / etc.

### Describe the solution you'd like

Move the images and videos we have to a separate branch.

**Comment by benoitf** [comment]
I still believe it's not part of this repository (branch would still be cloned by default) even if it would be convenient
could be an additional repo ?

**Comment by cdrage** [comment]
@benoitf that would be really beneficial as we do the same and rely on github cache for videos / pictures.

could you create a repo that is just generic "podman desktop assets" or something we can throw our videos / pictures in?

**Comment by cdrage** [comment]
PR here: https://github.com/containers/podman-desktop-media/pull/1
