### ISSUE TITLE
Add log button for builds on dashboard. 

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#677]
### Is your feature request related to a problem? Please describe

We should have a log button next to the delete button that loads up logs / essentially loads up with auto-refreshing the image log file (if it's available).

Multiple users have brought up "this doesn't work", but we have to explain to retrieve the image log file, it should be more accessible.

I encountered this a lot during implementing https://github.com/containers/podman-desktop-extension-bootc/issues/623 where having a direct button to logs would of been handy.

It should:
- Check that the log file exists
- Loads it
- Auto-refreshes

### Describe the solution you'd like

Log button that loads up image log (in a terminal?).

**Comment by benoitf** [comment]
hi, I'm not sure about which screen and which delete button you're referencing ?

**Comment by cdrage** [comment]
> hi, I'm not sure about which screen and which delete button you're referencing ?

On the dashboard we have the delete button beside any builds. 

We should have a log button beside it so it's more easily accessible / shows the current log of the build.
