### ISSUE TITLE
Fails root validation check when using macOS + libkrun

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#722]
### Bug description

Cannot build because it will show the "needs to be root" error.

This is because when using libkrun on macOS, `podman machine ls` will be blank.

We need to:

If we fail validation check and we are on macOS we should:
1. Use `podman system connection ls`
2. Find the default
3. Check the name has `-root`
4. If name does not have root, also check URI that the socket is `/run/podman`
5. Say that it's root podman machine if it passes either.

Luckily it is a validation check and if it it give a false positive, it will fail anyways in `bootc-image-builder` when building, as they ALSO have a validation check to make sure it's root.

### Operating system

mac m1

### Version

next (development version)

### Additional context

cc @cbr7

**Comment by cbr7** [comment]
@kush-gupt the issue can be worked around, if you add the libkrun provider to the `containers.conf` file of podman, then the `podman machine ls` will work and the error goes away.

**Comment by kush-gupt** [comment]
So I already have

```
[machine]
  provider = "libkrun"
```

in my `$HOME/.config/containers/containers.conf`

Is there a different containers.conf I need to update?

For reference, my output for `podman machine ls` is:
```
NAME                    VM TYPE     CREATED      LAST UP         CPUS        MEMORY      DISK SIZE
podman-machine-default  libkrun     4 weeks ago  18 minutes ago  6           11.18GiB    100GiB
```

**Comment by kush-gupt** [comment]
Fixed by removing my old machine using `podman machine rm`, creating a new one with `podman machine init`, set root with `podman machine set --rootful` and then finally `podman machine start`
