### ISSUE TITLE
Investigation: How to get examples from outside sources (bootc fedora examples)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#894]
### Is your feature request related to a problem? Please describe

How do we curate examples for bootc from existing repos https://gitlab.com/fedora/bootc/examples in order to showcase them?

### Describe the solution you'd like

Possibly use JSON file similar to AI lab, our own custom solution, etc. Will investigate.

**Comment by cdrage** [comment]
Investigating this, I believe we should follow a similar format as AI lab is doing with their easily updateable json file that they are using for showing the recipes.

https://github.com/containers/podman-desktop-extension-ai-lab/blob/main/packages/backend/src/assets/ai.json

![Image](https://github.com/user-attachments/assets/a201c7b4-1ada-44fa-99e7-68a67c4b1ef1)

Specifically, we would have similar fields that would showcase the location of the Containerfile, repo as well as folder so that we may more easily clone / copy the files over.

Categorization would be beneficial as well.. similar to how they have audio / recipes / etc for AI lab.

I was thinking the following fields:

```json
{
  "version": "1.0",
  "recipes": [
    {
      "id": "chatbot",
      "description" : "small description",
      "name" : "foobar",
      "repository": "https://gitlab.com/fedora/bootc/examples",
      "container": "quay.io/foo/bar",
      "basedir": "foo/bar",
      "containerfile": "Containerfile.rhel-9 / specific Containerfile to use in the repo",
      "ref": "v1.1.3 / main / etc / reference of what branch to use",
      "readme": "hello world markdown"
    },
```

This should give us enough information to start with when showing the initial information for the examples, etc.

We would point these to the fedora bootc examples to start / initial information.

cc @deboer-tim

**Comment by deboer-tim** [comment]
Is readme embedded or a uri/path? Maybe needs a categories or keywords for filtering.

nit: `branch` instead of `ref`?

Otherwise looks good to me.

TBH I don't want to suggest this, but ... should samples registry actually be part of Podman Desktop core or a shared extension, where anything can contribute to the list and bootc samples page is just a filtered view based on a keyword / category? AI Lab is a bit more complicated but we could use general / getting started samples too.

**Comment by cdrage** [comment]
> Is readme embedded or a uri/path? Maybe needs a categories or keywords for filtering.
> 
> nit: `branch` instead of `ref`?
> 
> Otherwise looks good to me.
> 
> TBH I don't want to suggest this, but ... should samples registry actually be part of Podman Desktop core or a shared extension, where anything can contribute to the list and bootc samples page is just a filtered view based on a keyword / category? AI Lab is a bit more complicated but we could use general / getting started samples too.

It's a simple JSON file.

What about doing it like podman desktop does with catalog and instead have it at a central location / website that users download / retrieve on initial open?

Meaning we do not have to do another release to update the default images / can update it remotely / etc.

**Comment by cdrage** [comment]
@deboer-tim 

So further investigation I think building via Containerfile will be a bad idea. 

I am building the nvidia example right now and it's been 15 minutes and counting...

I think that we should have it similar to how we do it now with pulling our example image.. it just pulls the image / has loading icon, then we can actually build it via the build page, etc.

My reasoning is that https://gitlab.com/fedora/bootc/examples/ is a meant as an assortment of "base images", and any changes that need to be done would be done via the configuration file: https://github.com/osbuild/bootc-image-builder?tab=readme-ov-file#users-user-array

My next question would be.. should we open an issue that we should maybe implement a "onboarding based view" for being able to generate the build config file with username / password / pre-stored SSH key on the build page?

Workflow I am thinking regarding examples page and build page:

1. View examples page
2. Click download for an examples image
3. Shows downloading logo
4. Changes to build
5. Click on "build"
6. Goes to build page with pre-selected examples image.
7. Select options / your username / password / etc.
8. Hit build
9. Yay bootable image!

**Comment by deboer-tim** [comment]
Yeah, that would work well. I think we'd still want mostly the same metadata (even if we don't build it, someone might want to go see the source?) plus info for the built image.

Generating/helping with build config would be nice and ties in well here, but I think we should track independently.

**Comment by cdrage** [comment]
> Yeah, that would work well. I think we'd still want mostly the same metadata (even if we don't build it, someone might want to go see the source?) plus info for the built image.
> 
> Generating/helping with build config would be nice and ties in well here, but I think we should track independently.

👍 agreed, I'll keep the same metadata so at least we can point to it / perhaps have a button in the future to download it, but otherwise pulling it via "pull image" would be more viable.

**Comment by cdrage** [comment]
I'm going to mark this as closed as I've investigated and discussed with @deboer-tim 

Looks like following a similar pattern to AI Lab would be best.

Please re-open if there is any other comments / concerns.
