### ISSUE TITLE
Image tag not passed to bootc-image-builder container

### ISSUE THREAD

**Issue by jwboyer** [containers/podman-desktop-extension-bootc#90]
### Bug description

I created an image following the Build steps in README.md but I added an explicit tag at the end of the image name.  The image build was successful, resulting in `quay.io/jwboyer/fedora-bootc:eln`.  I pushed that to quay and made the repository public.  However, I could not get the Build Disk Image functionality to work.

Looking at the image-build.log, I noticed the command passed to the bootc-image-build container only contained the repository name and did not include the :eln tag.  There was no :latest tag for this image in the repo, so bib failed to resolve it as it was trying to pull `quay.io/jwboyer/fedora-bootc` which didn't exist.

### Operating system

macOS Sonoma 14.2.1 M2 Pro

### Version

next (development version)

### Steps to reproduce

- Build a bootc image with an explicit tag
- Push the image to a public repository with no :latest equivalent
- Try to build a disk image from the newly created bootc image

### Relevant log output

```shell
Build Image Log --------
Image:  quay.io/jwboyer/fedora-bootc
Type:   raw
Folder: /Users/jboyer/images/desktop
----------
{
  "name": "fedora-bootc-bootc-image-builder",
  "Image": "quay.io/centos-bootc/bootc-image-builder:latest-1705709685",
  "Tty": true,
  "HostConfig": {
    "Privileged": true,
    "SecurityOpt": [
      "label=type:unconfined_t"
    ],
    "Binds": [
      "/Users/jboyer/images/desktop:/output/"
    ]
  },
  "Labels": {
    "bootc.image.builder": "true",
    "bootc.build.image.location": "/Users/jboyer/images/desktop/image/disk.raw",
    "bootc.build.type": "ami"
  },
  "Cmd": [
    "quay.io/jwboyer/fedora-bootc",
    "--type",
    "ami",
    "--output",
    "/output/"
  ]
}
----------
Generating manifest-ami.json ... panic: failed to resolve container: '': error getting manifest: reading manifest latest in quay.io/jwboyer/fedora-bootc: manifest unknown^M
^M
goroutine 1 [running]:^M
main.cmdBuild(0x400009d100?, {0x4000167340, 0x1, 0xb})^M
        /build/bib/cmd/bootc-image-builder/main.go:229 +0x83c^M
github.com/spf13/cobra.(*Command).execute(0x40003d8f00, {0x4000167290, 0xb, 0xb})^M
```

### Additional context

I've rectified this for my images by pushing a :latest image and building from that.  I tried to figure out how to pass the actual tag from the image into the command for the bib container, but I'm not familiar enough with the code.  In the screenshot below, the top image works and the third in the list failed before I generated the :latest tag.  Notably, if I build it now it will succeed, but it doesn't actually use the specific :eln hash.  Looking in the successful log, it fetches the latest image instead of :eln

<img width="1049" alt="image" src="https://github.com/containers/podman-desktop-extension-bootc/assets/1058117/07e93a40-1902-4f86-acca-707075a89f4b">

**Comment by jwboyer** [comment]
I should note that this was also after I debugged an issue with @deboer-tim earlier and had #88 applied locally.

**Comment by deboer-tim** [comment]
Yes... we hadn't tested tagged images yet. The fix is incredibly simple, you can pull the two lines from the draft PR, and I'll try to write tests and get it in tomorrow.

**Comment by jwboyer** [comment]
Tested #91 with a new `quay.io/jwboyer/centos-bootc:stream9` image and it was able to build a disk image.  Thanks for the quick turn around!
