### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#93]
### Is your enhancement related to a problem? Please describe

It should work on linux

### Describe the solution you'd like

working on linux

**Comment by cdrage** [comment]
At the moment we are blocked on two issues:

https://github.com/containers/podman-desktop/issues/2861 which involves not being able to run rootful containers on linux systems.

and 

https://github.com/osbuild/bootc-image-builder/issues/98 which doesn't allow building containers on a rootless container.

We'd have to fix one of the issues to get this functionality to work on linux.

You can perform the build no problem via CLI with `sudo`, but we are unable to perform the build through podman desktop at the moment.

**Comment by cdrage** [comment]
We can now create root podman machines on Linux on Podman Desktop: https://github.com/containers/podman-desktop/issues/5823

So we can use bootc-image-builder on Linux now.

We however, must have documentation / ample notifications indicating that you need a rootful Linux machine to do this.

**Comment by cgwalters** [comment]
I think documenting the requirement for a rootful machine is OK at this time.

**Comment by vrothberg** [comment]
Documenting the requirements sounds good to me.  The extension could also throw a warning if the machine runs rootless.

**Comment by vrothberg** [comment]
@cdrage I don't see that the requirement on running as root inside the machine has been addressed with #186.  Am I missing something?

**Comment by cdrage** [comment]
> @cdrage I don't see that the requirement on running as root inside the machine has been addressed with #186. Am I missing something?

It's been added to the readme: https://github.com/containers/podman-desktop-extension-bootc?tab=readme-ov-file#requirement-2-rootful-mode-on-podman-machine

It was always there, but now we just added the "works on Linux" part / you must create a Linux machine.

**Comment by cdrage** [comment]
Created https://github.com/containers/podman-desktop-extension-bootc/pull/187 to add more detail regarding Linux support, as you are right however, there is limited information in the docs / requirements that were missing.
