### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#94]
### Is your enhancement related to a problem? Please describe

at the moment doedsnt work on windows

### Describe the solution you'd like

working on windows.

**Comment by deboer-tim** [comment]
Tested all options on Windows and it all (*) worked fine. I was able to build RAW, AMI, and QCOW without issues:

![bootc-windows](https://github.com/containers/podman-desktop-extension-bootc/assets/19958075/71e6100a-d161-4b26-81d4-44d50343fb18)

I did find some minor nits that aren't platform-specific (e.g. end dialog gives you OK and Cancel options... but they don't make any difference) and will open a PR later. Also ran into #149, which is not platform-specific.
