### ISSUE TITLE
add a release workflow

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-bootc#97]
### Is your enhancement related to a problem? Please describe

releases should have their own Github Action workflow

### Describe the solution you'd like

add the release job to tag, build the image and publish it under the tag name and `latest`

**Comment by deboer-tim** [comment]
v0.1.0 released, and everything appears to have worked - CI pushes tagged versions only to nightly, and release build does all the proper tagging (version + latest), pushing, and PRs version updating. The worst problem I can find is that the bot says "has been released." (missing what version was released :) will PR), so I'm counting this as done.
